apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: voting-backend-service
    environment: production
  namespace: voting-app
spec:
  selector:
    app: voting-backend-pod
    environment: production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer