apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: voting-db-service
    environment: production
  namespace: voting-app
spec:
  selector:
    role: mongo-pod
    environment: production
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None